### PR TITLE
fix: populate primaryOrderDeliveryId and primaryOrderTransactionId in OrderConverter

### LINKED ISSUE #14051: Order overview don't show payment state, delivery state and delivery address
### Shopware Version

6.7.5.1

### Affected area / extension

Extension:Migration-Tool

### Actual behaviour

If You migrate a Shopware 5 to the newest Shopware 6.7.5.1 version, you don't see the payment state, delivery state or delivery address in the orders overview. If you go to details, all data are available.

Image

Image

### Expected behaviour

Show the payment state, delivery state and delivery address if available. It looks that the` primary_order_transaction_id` and `primary_order_delivery_id` not filled with a reference

```json
{
    "attributes": {
        "versionId": "0fa91ce3e96a4bc2be4bd9ce752c3425",
        "autoIncrement": 1234,
        "orderNumber": "123456",
        "billingAddressId": "019b1cc82a627266aea75a2d7a8dc1a6",
        "billingAddressVersionId": "0fa91ce3e96a4bc2be4bd9ce752c3425",
        "primaryOrderDeliveryId": null,
        "primaryOrderDeliveryVersionId": "0fa91ce3e96a4bc2be4bd9ce752c3425",
        "primaryOrderTransactionId": null,
        "primaryOrderTransactionVersionId": "0fa91ce3e96a4bc2be4bd9ce752c3425",
        "currencyId": "b7d2554b0ce847cd82f3ac9bd1c0dfca",
        "languageId": "2fbb5fe2e29a4d70aa5854ce7ce3e20b",
        "salesChannelId": "019b1cc74ba9737a970a83a74598e696",
        "orderDateTime": "2025-12-13T10:01:04.000+00:00",
        "orderDate": "2025-12-13T00:00:00.000+00:00",
        ...
}
```

### How to reproduce

Make a migration in the current 6.7.5.2

### PR DESCRIPTION
**Pull request by MnkyArts**
### 1. Why is this change necessary?

closes https://github.com/shopware/shopware/issues/14051

The Migration Assistant does not populate the `primaryOrderDeliveryId` and `primaryOrderTransactionId` fields when migrating orders from Shopware 5 to Shopware 6. These fields were introduced in Shopware 6.7 and are required for proper order handling.

### 2. What does this change do, exactly?

This change updates both OrderConverters to set the primary order delivery and transaction IDs:

- **Shopware 5 → 6 (`Profile/Shopware/Converter/OrderConverter.php`)**: Sets `primaryOrderDeliveryId` to the first delivery's ID and `primaryOrderTransactionId` to the first transaction's ID after they are created.

- **Shopware 6 → 6 (`Profile/Shopware6/Converter/OrderConverter.php`)**: Sets `primaryOrderDeliveryId` and `primaryOrderTransactionId` from the first delivery/transaction if deliveries and transactions exist.

This mirrors the behavior of Shopware 6's core `OrderConverter` which sets these fields when converting a cart to an order.

### 3. Describe each step to reproduce the issue or behaviour.

1. Set up a Shopware 5 shop with existing orders
2. Install the Migration Assistant in a Shopware 6.7+ shop
3. Run a migration for orders
4. Check the migrated orders in the database: `SELECT id, primary_order_delivery_id, primary_order_transaction_id FROM \`order\``
5. **Before fix**: Both fields are `NULL`
6. **After fix**: Both fields are populated with the correct delivery/transaction IDs

### 5. Checklist

- [x] I have created the PR in draft status and only open it when it's ready for review
- [x] If the change is large: I have thought about splitting it up into smaller PRs
- [x] I have written tests and if it's a bug fix verified that they fail without my change or that new code is covered by tests
- [ ] I have updated developer-facing release notes if this change affects external developers
- [ ] I have written or adjusted the documentation according to my changes
- [x] I added the correct package annotation to each `src` file (not strictly necessary for tests)
- [x] This change has code comments where appropriate, especially for non-obvious lines of code
- [x] Ensure the pull request title as well as first commit follows conventional commits
- [x] I have thought about well-defined extension points and marked everything else as `@internal` / `@private`

### CODE REVIEW

**Review by jozsefdamokos — APPROVED** [review]

**Review by shyim — APPROVED** [review]

**Review by larskemper — APPROVED** [review]

File: src/Profile/Shopware6/Converter/OrderConverter.php [hunk 1]
```diff
@@ -161,6 +161,13 @@ protected function convertData(array $data): ConvertStruct
             $converted['updatedById'] = $this->getMappingIdFacade(DefaultEntities::USER, $data['updatedById']);
         }
 
+        if (!isset($converted['primaryOrderDeliveryId']) && !empty($converted['deliveries'])) {
+            $converted['primaryOrderDeliveryId'] = $converted['deliveries'][0]['id'];
+        }
+        if (!isset($converted['primaryOrderTransactionId']) && !empty($converted['transactions'])) {
+            $converted['primaryOrderTransactionId'] = $converted['transactions'][0]['id'];
```
Comment (MalteJanz) [inline src/Profile/Shopware6/Converter/OrderConverter.php:168]: Looks like PHPStan isn't happy about this, because it thinks the array has a shape of `array<string,mixed>` as defined here:

https://github.com/shopware/SwagMigrationAssistant/blob/5a9afd81133508891430770194d4ee94d41ce6cc/src/Profile/Shopware6/Converter/OrderConverter.php#L104-L109

https://github.com/shopware/SwagMigrationAssistant/blob/5d4ec50b03152b8433e76cd8eddbb4cf87167905/src/Profile/Shopware6/Converter/ShopwareConverter.php#L128-L132

But like in this case, in practice it can also have integer keys. Would be nice if you could fix this to get the CI checks green 🙂

**Review by MalteJanz — COMMENTED** [review]
Thanks for the contribution 🚀

**Review by vintagesucks — APPROVED** [review]

File: src/Profile/Shopware6/Converter/OrderConverter.php (hunk 1 above)
Comment (MnkyArts) [reply src/Profile/Shopware6/Converter/OrderConverter.php:168]: Gonna need to find some time, but going to do it :)

Comment (vintagesucks) [reply src/Profile/Shopware6/Converter/OrderConverter.php:168]: We resolved the PHPStan issue, thanks again for the contribution 🚀

**Review by MalteJanz — APPROVED** [review]

File: src/Profile/Shopware6/Converter/OrderConverter.php (hunk 1 above)
Comment (MnkyArts) [reply src/Profile/Shopware6/Converter/OrderConverter.php:168]: Thanks for continuing it! Would've loved to resolve it myself but live & work got busy.
