### PR TITLE
fix: connection name with hypens

### LINKED ISSUE #8013: Do a major Assistant + Magento Release to support the RC1 of 6.7
Now that the plugins are compatible in the {{trunk}}branch with shopware 6.7 we should do another release of them

### LINKED ISSUE #9155: custom-fields are no longer migrated when the connection-name contains a hyphen
### Shopware Version

6.7.0.1 (probably the same in 6.7.0.0)

### Affected area / extension

Extension:Migration-Tool

### Actual behaviour

The migration of custom fields/attributes fails if the connection name contains a string with a hyphen like "my-connection"

These errors are thrown:
```
[error] SWAG_MIGRATION_RUN_EXCEPTION
An exception occurred
Entity: order_custom_field, sourceId: 0196ae9e37017342be821ea520451f7b
Invalid custom field name: It must begin with a letter or underscore, followed by letters, numbers, or underscores.
```
This change was done in this commit: https://github.com/shopware/shopware/commit/bd8e1d0f7895e7089d8fb750a02377f6f747b6fa

We build a new technical name for the custom fields and sets, which includes the connection name: (https://github.com/shopware/SwagMigrationAssistant/blob/e520d0985342b7fce5a07458267a81bed05f9997/src/Profile/Shopware/Converter/AttributeConverter.php#L61
We could validate this before saving the values or replace the hyphen with an underscore or something else.

### Expected behaviour

Custom fields should still be migrated as before 6.7.0.1.

### How to reproduce

- insert a string with a hyphen when creating the connection to the source system
Image

### PR DESCRIPTION
**Pull request by jozsefdamokos**
fixes [#9155](https://github.com/shopware/shopware/issues/9155)

fixes https://github.com/shopware/shopware/issues/8013

### CODE REVIEW

File: src/Resources/app/administration/src/module/swag-migration/page/swag-migration-data-selector/index.js [hunk 1]
```diff
@@ -38,15 +38,15 @@ Component.register('swag-migration-data-selector', {
         },
 
         fetchTableData() {
-            if (this.dataSelectionTableData.length > 0) {
-                this.$nextTick(() => {
```
Comment (jozsefdamokos) [inline src/Resources/app/administration/src/module/swag-migration/page/swag-migration-data-selector/index.js:42]: For some reason this is now running into an infinite loop causing the page to freeze and crash. I added a `setTimeout` now to wait until the ref is available. If there are better solutions let me know. I tried multiple `$nextTick()` methods but it did not work.

@shopware/product-ct-admin any ideas?

**Review by ennasus4sun — APPROVED** [review]

File: src/Resources/app/administration/src/module/swag-migration/page/swag-migration-data-selector/index.js (hunk 1 above)
Comment (jleifeld) [reply src/Resources/app/administration/src/module/swag-migration/page/swag-migration-data-selector/index.js:42]: `setTimeout` is not really a solution. I think it makes more sense to debug (using the Chrome devtools) the issue of the infinite loop. Because a hotfix like this will lead to other problems in the future

File: src/Migration/Connection/Helper/ConnectionNameSanitizer.php [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+class ConnectionNameSanitizer
+{
+    /**
+     * Sanitizes the connection name by removing any special characters, hyphens and spaces.
+     * Only alphanumeric characters are allowed.
+     */
+    public static function sanitize(string $connectionName): string
+    {
+        return \preg_replace('/[^a-zA-Z0-9]/', '', \str_replace([' ', '-'], '', $connectionName));
+    }
```
Comment (MalteJanz) [inline src/Migration/Connection/Helper/ConnectionNameSanitizer.php]: LGTM 👍 , we could optionally mention why this constraint exists in the first place: we sometimes use the connection name in places where a unique technical name is needed and e.g. CustomFields have their own constraints on names, see
https://github.com/shopware/shopware/blob/df7ae4bf10431177298ed5bd8e32a6da0ba3c93f/src/Core/System/CustomField/CustomFieldService.php#L29

File: src/Resources/app/administration/src/module/swag-migration/page/swag-migration-data-selector/index.js (hunk 1 above)
Comment (MalteJanz) [reply src/Resources/app/administration/src/module/swag-migration/page/swag-migration-data-selector/index.js:42]: We can take a closer look together if you like, I'm also not feeling well with the `setTimeout` workaround, even `$nextTick` wasn't that great to begin with but might have been necessary 🤷‍♂️

**Review by MalteJanz — APPROVED** [review]

File: CHANGELOG_de-DE.md [hunk 3]
```diff
@@ -1,3 +1,7 @@
+# 15.0.2
+- Einfrieren der Datenauswahl-Registerkarte aufgrund einer Endlosschleife behoben
```
Comment (jozsefdamokos) [inline CHANGELOG_de-DE.md]: Any suggestions?

File: CHANGELOG.md [hunk 4]
```diff
@@ -1,3 +1,7 @@
+# 15.0.2
+- Fixed data selection tab freezing due to infinite loop
```
Comment (MalteJanz) [inline CHANGELOG.md]:
```suggestion
- Fixed data selection tab freezing due to infinite loop in SW6.7RC4 or later
```

File: CHANGELOG_de-DE.md (hunk 3 above)
Comment (MalteJanz) [inline CHANGELOG_de-DE.md]:
```suggestion
- Einfrieren des Browsers im Datenauswahl-Tab aufgrund einer Endlosschleife ab SW6.7RC4 behoben
```

**Review by MalteJanz — APPROVED** [review]

**Review by ennasus4sun — APPROVED** [review]

**Review by MalteJanz — APPROVED** [review]
